# Generated by Django 3.2.9 on 2022-01-11 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import show.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=show.models.upload_show_cat)),
            ],
        ),
        migrations.CreateModel(
            name='ShowSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=show.models.upload_show_subcat)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_cat', to='show.showcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=show.models.upload_show)),
                ('banner', models.FileField(blank=True, upload_to=show.models.upload_show)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('video', models.FileField(blank=True, upload_to=show.models.upload_show)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.showcategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.showsubcategory')),
            ],
        ),
    ]
