# Generated by Django 3.2.9 on 2022-01-09 09:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('owner', models.TextField(blank=True)),
                ('target', models.PositiveIntegerField()),
                ('image', models.FileField(max_length=255, upload_to=api.models.banner_advert)),
            ],
        ),
        migrations.CreateModel(
            name='GTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('image', models.FileField(max_length=255, upload_to=api.models.live_video)),
            ],
        ),
        migrations.CreateModel(
            name='PTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField(blank=True)),
                ('skip', models.BooleanField(default=False)),
                ('image', models.FileField(max_length=255, upload_to=api.models.video_advert)),
                ('video', models.FileField(max_length=255, upload_to=api.models.video_advert)),
            ],
        ),
    ]
