# Generated by Django 3.2.9 on 2022-01-10 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=movie.models.upload_movie_cat)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=movie.models.upload_movie_genre)),
            ],
        ),
        migrations.CreateModel(
            name='MovieProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=movie.models.upload_movie_producer)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('phone', models.TextField(blank=True)),
                ('reports', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieReels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=movie.models.upload_movie_reels)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('video', models.FileField(blank=True, upload_to=movie.models.upload_movie_reels)),
            ],
        ),
        migrations.CreateModel(
            name='MovieSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=movie.models.upload_movie_subcat)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=movie.models.upload_movie)),
                ('banner', models.FileField(blank=True, upload_to=movie.models.upload_movie)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('video', models.FileField(blank=True, upload_to=movie.models.upload_movie)),
                ('Price', models.FloatField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movieCat', to='movie.moviecategory')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.moviegenre')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviesubcategory')),
            ],
        ),
    ]
